# Generated by Django 5.2.12 on 2026-03-27 23:00

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=180, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание категории')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать категорию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MineCatalog', max_length=120, verbose_name='Название сайта')),
                ('site_tagline', models.CharField(blank=True, max_length=220, verbose_name='Подзаголовок сайта')),
                ('default_seo_title', models.CharField(blank=True, max_length=180, verbose_name='SEO title по умолчанию')),
                ('default_seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO description по умолчанию')),
                ('footer_text', models.TextField(blank=True, verbose_name='Текст в футере')),
                ('contacts_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('contacts_telegram', models.CharField(blank=True, max_length=120, verbose_name='Telegram')),
                ('copyright_text', models.CharField(blank=True, max_length=220, verbose_name='Копирайт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('body', models.TextField(blank=True, verbose_name='Содержимое')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('show_in_nav', models.BooleanField(default=False, verbose_name='Показывать в верхнем меню')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать в футере')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Например: home_intro, home_bottom_text, contacts_note', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Используйте только строчные латинские буквы, цифры и _.', regex='^[a-z0-9_]+$')], verbose_name='Ключ')),
                ('title', models.CharField(max_length=120, verbose_name='Название блока')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Текстовый блок',
                'verbose_name_plural': 'Текстовые блоки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя / название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('status_label', models.CharField(blank=True, help_text='Например: подтверждено, спорно, редакционная оценка', max_length=80, verbose_name='Статус / метка')),
                ('short_caption', models.CharField(blank=True, max_length=220, verbose_name='Короткая подпись')),
                ('image', models.ImageField(blank=True, upload_to='people/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), catalog.models.validate_image_size], verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Основное описание')),
                ('reasoning', models.TextField(blank=True, verbose_name='Почему мы так считаем')),
                ('extra_information', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('sources_notes', models.TextField(blank=True, verbose_name='Источники / примечания')),
                ('editorial_note', models.TextField(blank=True, help_text='Например: информация носит оценочный/редакционный характер.', verbose_name='Редакционное примечание')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_published', 'show_on_homepage'], name='catalog_per_is_publ_461baf_idx'), models.Index(fields=['slug'], name='catalog_per_slug_52dd36_idx')],
            },
        ),
    ]
